feat(Task-20): As a Product Manager, I want to increase the potential users of my application
jLagosCarrera/MeteoApp pull request #19
Opened 2019-05-30 13:29 UTC by jLagosCarrera

2019-05-30 14:05 UTC, eloydotco requested changes

2019-05-30 14:05 UTC, eloydotco commented on src/app/shared/filters/capitalize.js
> +    if (!input) return '';
Please, use the complete `if {} else {}` format

2019-05-30 14:05 UTC, gbtec-ext-eloycastelo commented on src/app/shared/filters/capitalize.js
> +
and remove this empty line

2019-05-30 14:05 UTC, gbtec-ext-eloycastelo commented on src/app/shared/filters/capitalize.js
> +        txt.charAt(0).toUpperCase() + txt.substr(1).toLowerCase());
don't break arrow functions

2019-05-30 14:05 UTC, gbtec-ext-eloycastelo commented on src/resources/translations/es.js
> +            "SEND_ISSUE": "Envia el problema"
typo :)

2019-05-30 14:05 UTC, gbtec-ext-eloycastelo commented on src/resources/translations/gl.js
> +            "SEND_ISSUE": "Envia o problema"
typo :)

2019-05-30 14:13 UTC, eloydotco approved these changes

2019-05-31 09:02 UTC, gbtec-ext-jorgevillar requested changes

2019-05-31 09:02 UTC, gbtec-ext-jorgevillar commented on src/app/shared/filters/capitalize.js
> +}
I'm glad you use Filters, but I think you can do this with a CSS style way more easy:
`<selector> {
    text-transform: capitalize;
}`

2019-05-31 09:02 UTC, gbtec-ext-jorgevillar commented on src/app/home-page/homePage.component.html
> +        list-type="{{ ::'DISPLAYABLE_LIST.TYPES.RECENT' | translate }}">
What happens with the one time binding in the next story (about placing a switch laguage behavior)? Please, take care of this

2019-05-31 09:02 UTC, gbtec-ext-jorgevillar commented on src/app/search-page/searchPage.component.html
> +                    list-type="{{ ::'DISPLAYABLE_LIST.TYPES.RECENT' | translate }}"></displayable-list>
Same as above

2019-05-31 09:02 UTC, gbtec-ext-jorgevillar commented on src/app/search-page/searchPage.component.html
> +                    list-type="{{ ::'DISPLAYABLE_LIST.TYPES.NEARBY' | translate }}"></displayable-list>
Same as above

2019-05-31 09:02 UTC, gbtec-ext-jorgevillar commented on src/resources/translations/es.js
> +            "RECENT": "reciente"
In English this to translations are capitalized

2019-05-31 09:02 UTC, gbtec-ext-jorgevillar commented on src/resources/translations/es.js
> +            "HEADER": "lista de ciudades {{ type }}s",
Shouldn,t this start with a capital letter?

2019-05-31 09:02 UTC, gbtec-ext-jorgevillar commented on src/resources/translations/es.js
> +        "CONTACT_BUTTON": "Necesitas ayuda?",
missing '¿' at the beginning

2019-05-31 09:02 UTC, gbtec-ext-jorgevillar commented on src/resources/translations/gl.js
> +}
Same requests as the espanish translation

2019-05-31 11:06 UTC, jLagosCarrera commented on src/app/shared/filters/capitalize.js
> +}
We already talked about it, new issue for this 👌

2019-05-31 11:12 UTC, jLagosCarrera commented on src/resources/translations/es.js
> +            "RECENT": "reciente"
Different use on English and Spanish, that's why it isn't capitalized

2019-05-31 12:18 UTC, gbtec-ext-jorgevillar approved these changes

2019-05-31 12:18 UTC, gbtec-ext-jorgevillar commented on src/resources/translations/es.js
> +            "RECENT": "recente"
'Reciente' was right

2019-05-31 12:26 UTC, merged