feat(Task-14): As a User, I want to get a suggestion list of cities when I write on a search input.
jLagosCarrera/MeteoApp pull request #31
Opened 2019-06-05 11:33 UTC by jLagosCarrera

2019-06-05 12:51 UTC, gbtec-ext-jorgevillar requested changes
Fix search button

2019-06-05 12:51 UTC, gbtec-ext-jorgevillar commented on src/app/shared/components/displayable-list/displayableList.controller.js
> +        console.log(city)
Remove log

2019-06-05 12:51 UTC, gbtec-ext-jorgevillar commented on src/app/shared/services/geoNames.js
>                  maxRows: maxRows,
You can write these three in the ES6

2019-06-05 13:08 UTC, gbtec-ext-jorgevillar approved these changes

2019-06-05 13:44 UTC, eloydotco approved these changes

2019-06-05 14:18 UTC, merged

2019-06-06 10:16 UTC, jLagosCarrera commented
#16 solved here

2019-06-07 07:14 UTC, jLagosCarrera commented
#15 solved here aswell