feat(Task-4): As a Developer, I want to have the openWeatherMap api configured
jLagosCarrera/MeteoApp pull request #4
Opened 2019-05-02 10:58 UTC by jLagosCarrera

2019-05-02 14:57 UTC, eloydotco requested changes
Solve conflicts also

2019-05-02 14:57 UTC, eloydotco commented on src/app/app.component.js
> +function AppComponentController($scope, weatherService) {
It's a good practice create another file for the controller -> `app.controller.js`

2019-05-02 14:57 UTC, eloydotco commented on src/app/app.module.js
> +app.factory('weatherService', ['$http', function ($http) {
Another good practice is create a new file for each new service, and put all on a `services` folder. Very good for write maintainable code

2019-05-03 07:13 UTC, gbtec-ext-jorgevillar requested changes

2019-05-03 07:13 UTC, gbtec-ext-jorgevillar commented on src/app/app.component.js
> +function AppComponentController($scope, weatherService) {
+1 to Eloy and in plus of that, create it in the EcmaScrip2015 way (with a class)
![image](https://user-images.githubusercontent.com/37654233/57122898-e1ea1780-6d7f-11e9-995c-77944edacc8e.png)

2019-05-03 08:01 UTC, diegopf requested changes

2019-05-03 08:01 UTC, diegopf commented on src/app/app.module.js
> +                appid: '37499dd44886aa89565abd094ecbfc8c'
This repository is public, isn't? :) You must not commit such things as passwords or apikeys into public repositories. You can take a look at https://webpack.js.org/plugins/define-plugin/

2019-05-03 09:34 UTC, jLagosCarrera commented
All requested changes done

2019-05-03 09:42 UTC, eloydotco approved these changes

2019-05-03 10:04 UTC, diegopf approved these changes

2019-05-03 10:12 UTC, merged